# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: call_pi.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='call_pi.proto',
  package='grpc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rcall_pi.proto\x12\x04grpc\"\x1a\n\tPiRequest\x12\r\n\x05image\x18\x01 \x01(\t\"%\n\x07PiReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t29\n\tPiService\x12,\n\x08SendData\x12\x0f.grpc.PiRequest\x1a\r.grpc.PiReply\"\x00\x62\x06proto3'
)




_PIREQUEST = _descriptor.Descriptor(
  name='PiRequest',
  full_name='grpc.PiRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='grpc.PiRequest.image', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=49,
)


_PIREPLY = _descriptor.Descriptor(
  name='PiReply',
  full_name='grpc.PiReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='grpc.PiReply.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='grpc.PiReply.data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['PiRequest'] = _PIREQUEST
DESCRIPTOR.message_types_by_name['PiReply'] = _PIREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PiRequest = _reflection.GeneratedProtocolMessageType('PiRequest', (_message.Message,), {
  'DESCRIPTOR' : _PIREQUEST,
  '__module__' : 'call_pi_pb2'
  # @@protoc_insertion_point(class_scope:grpc.PiRequest)
  })
_sym_db.RegisterMessage(PiRequest)

PiReply = _reflection.GeneratedProtocolMessageType('PiReply', (_message.Message,), {
  'DESCRIPTOR' : _PIREPLY,
  '__module__' : 'call_pi_pb2'
  # @@protoc_insertion_point(class_scope:grpc.PiReply)
  })
_sym_db.RegisterMessage(PiReply)



_PISERVICE = _descriptor.ServiceDescriptor(
  name='PiService',
  full_name='grpc.PiService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=90,
  serialized_end=147,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendData',
    full_name='grpc.PiService.SendData',
    index=0,
    containing_service=None,
    input_type=_PIREQUEST,
    output_type=_PIREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PISERVICE)

DESCRIPTOR.services_by_name['PiService'] = _PISERVICE

# @@protoc_insertion_point(module_scope)
